version: "3"

services: 
  ultra-sample:
    container_name: ultra-sample
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    links:
        - ultra-mongo
    volumes: 
        - .:/usr/src/app
  ultra-mongo:
    container_name: ultra-mongo
    image: mongo
    ports: 
        - "27017:27017"
    logging:
      driver: none
    volumes:
        - ultra-mongo-data:/data/db
volumes:
  ultra-mongo-data: