version: "3"

services: 
  ultra-sample:
    container_name: ultra-sample
    restart: always
    build: .
    ports:
        - "3000:3000"
    links:
        - ultra-mongo
    volumes: 
        - .:/usr/src/app
  ultra-mongo:
    container_name: ultra-mongo
    image: mongo
    ports: 
        - "27017:27017"
    logging:
      driver: none